version: "2.2"
services:
    react-client:
        container_name: react_app
        build: 
            context: "./client"
            dockerfile: Dockerfile
        volumes: 
            - ".client:/app"
            - "/app/node_modules"
        ports:
            - 3000:3000
        environment: 
            - CHOKIDAR_USEPOLLING=true
    node_sever:
        container_name: node_server_app
        build: 
            context: "./server"
            dockerfile: Dockerfile
        ports: 
            - 5000:5000
        volumes:
            - "./server/app"
            - "/app/node_modules"
        environment:
                - CHOKIDAR_USEPOLLING=trues